services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Lemonmind\PimcoreLocalizedAssetsBundle\Configuration\Configuration: ~

    Lemonmind\PimcoreLocalizedAssetsBundle\Installer:
        public: true
        arguments:
            $bundle: "@=service('kernel').getBundle('PimcoreLocalizedAssetsBundle')"