services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Lemonmind\PimcoreLocalizedAssetsBundle\Controller\:
        resource: '../../Controller/*'
        public: true
        tags: [ 'controller.service_arguments' ]

    Lemonmind\PimcoreLocalizedAssetsBundle\Configuration\Configuration: ~

    Lemonmind\PimcoreLocalizedAssetsBundle\Installer:
        public: true
        arguments:
            $bundle: "@=service('kernel').getBundle('PimcoreLocalizedAssetsBundle')"